### ISSUE TITLE
Streaming data: SSL peer shut down incorrectly

### ISSUE THREAD

**Issue by GoogleCodeExporter** [runt18/google-bigquery#115]
```
To who may concern:

Bigquery API version: bigquery-v2r147lv1.16.0-rc
Running on Eclipse 4.3 R2, Windows Server 2008 R2

In my ExecutorService, whenever a task(containing data to stream) is available, 
the executor will activate a thread to send a stream request to Google 
Bigquery. I found after a while,  it threw exception: 

    javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake
    at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:973)
    at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1343)
    at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1371)
    at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1355)
    at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:563)
    at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
    at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1281)
    at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1256)
    at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:250)
    at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:77)
    at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:964)
    at com.google.api.client.auth.oauth2.TokenRequest.executeUnparsed(TokenRequest.java:283)
    at com.google.api.client.auth.oauth2.TokenRequest.execute(TokenRequest.java:307)
    at com.google.api.client.googleapis.auth.oauth2.GoogleCredential.executeRefreshToken(GoogleCredential.java:269)
    at com.google.api.client.auth.oauth2.Credential.refreshToken(Credential.java:489)
    at com.google.api.client.auth.oauth2.Credential.intercept(Credential.java:217)
    at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:858)
    at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:410)
    at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:343)
    at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:460)
    at com.geotab.bigdata.bqstream.util.BigqueryHelper.submitStreamRequest(BigqueryHelper.java:79)
    at com.geotab.bigdata.bqstream.pipeline.RequestSendTask.run(RequestSendTask.java:47)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
    Caused by: java.io.EOFException: SSL peer shut down incorrectly
    at sun.security.ssl.InputRecord.read(InputRecord.java:505)
    at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:954)
    ... 26 more

I assumed that it was because I didn't refresh my credentials. So I updated my 
code as in the attachment. But it didn't help to solve the problem. I check 
google API doc(https://developers.google.com/drive/web/credentials). But it 
only provides the way for a web app account. But what I use is a service 
account for a Java application. 

Or my problem is not due to credential at all? How can I solve it?

Please help me out. Thanks so much



```

Original issue reported on code.google.com by `fionaz...@geotab.com` on 8 Jul 2014 at 6:22

Attachments:
- [BigqueryHelper.java](https://storage.googleapis.com/google-code-attachments/google-bigquery/issue-115/comment-0/BigqueryHelper.java)

**Comment by GoogleCodeExporter** [comment]
```
Hi Fiona, I apologize for the late response.  Is this still an issue for you?
```

Original comment by `thomasp...@google.com` on 21 Aug 2014 at 12:36

**Comment by GoogleCodeExporter** [comment]
```
Hi, not any more, thx
ᐧ

*Fiona Zhao*
Geotab Inc.
Big Data Analyst & Developer Intern

[Direct] +1 (647) 728-4484
[Toll-Free] +1 (877) 436-8221
[Visit] www.geotab.com
Twitter <http://twitter.com/geotab> | Facebook
<http://www.facebook.com/mygeotab> | YouTube
<http://www.youtube.com/mygeotab> | LinkedIn
<http://www.linkedin.com/company/102661?trk=tyah&trkInfo=tarId:1403199250031,tas
:geotab,idx:2-1-3>
```

Original comment by `fionaz...@geotab.com` on 21 Aug 2014 at 1:22

**Comment by GoogleCodeExporter** [comment]
Original comment by `roselan...@google.com` on 21 Aug 2014 at 4:20
- Changed state: **WontFix**

**Comment by GoogleCodeExporter** [comment]
```
How did you solve this error?
```

Original comment by `pareshwa...@gmail.com` on 26 Jun 2015 at 12:19

**Comment by GoogleCodeExporter** [comment]
```
it ended up to be some network issue on our side, not from bigquery side. it 
was when we were using a virtual machine that we found this error way more 
frequently
```

Original comment by `fionaz...@geotab.com` on 26 Jun 2015 at 1:17
