### ISSUE TITLE
InsertAll streaming API fails with 500 Backend error

### ISSUE THREAD

**Issue by GoogleCodeExporter** [runt18/google-bigquery#118]
```
What steps will reproduce the problem?
1.I have scheduler that pushes 500 Rows to the same table at every 2 seconds
2.Till some batches(say 20 or 30 or 40..) it works fine; but after that it 
throws following exception
com.google.api.client.googleapis.json.GoogleJsonResponseException: 500 Internal 
Server Error
{
  "code" : 500,
  "errors" : [ {
    "domain" : "global",
    "message" : "Backend Error",
    "reason" : "backendError"
  } ],
  "message" : "Backend Error"
}
with the following stacktrace:
at 
com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJso
nResponseException.java:145)
    at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:113)
    at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:40)
    at com.google.api.client.googleapis.services.AbstractGoogleClientRequest$1.interceptResponse(AbstractGoogleClientRequest.java:312)
    at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1049)
    at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:410)
    at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:343)
    at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:460)

We are using google-api-services-bigquery v2-rev149-1.18.0-rc


```

Original issue reported on code.google.com by `livestre...@livestream.com` on 16 Jul 2014 at 6:15

**Comment by GoogleCodeExporter** [comment]
```
I also regularly have this error. Retrying works but would be nice to reduce 
this error rate. This happens to me in average once every 1,000 api calls to 
insertAll.
```

Original comment by `ale...@freshplanet.com` on 21 Jul 2014 at 10:37

**Comment by GoogleCodeExporter** [comment]
```
Thank you, I have filed an internal ticket on your behalf.

Could you please let us know what your cloud project ids are, and what dataset 
+ tables you are writing to?
```

Original comment by `thomasp...@google.com` on 22 Aug 2014 at 9:19
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
In my case, requests are made from "Project ID: freshplanet.com:megapop-api 
Project Number: 567673786294", to dataset & tables in many different projects, 
including itself.

The project to which we write the most is: "Project ID: wam-mobile Project 
Number: 919944390759". In this project, the most solicited table is probably 
[events.prod_loading_quiz]
```

Original comment by `ale...@freshplanet.com` on 25 Aug 2014 at 10:31

**Comment by GoogleCodeExporter** [comment]
```
We've made lots of improvements to streaming ingestion since this bug was 
filed. If you are still experiencing issues, please let us know. (Though keep 
in mind that there is likely to be some small background error rate of < 0.1% 
under normal circumstances, so you should expect to retry some requests on the 
client side.)
```

Original comment by `jcon...@google.com` on 23 Jun 2015 at 4:36
- Changed state: **Done**
