### ISSUE TITLE
BigQuery Access from AppEngine is timeouted several times during last week

### ISSUE THREAD

**Issue by GoogleCodeExporter** [runt18/google-bigquery#23]
```
What steps will reproduce the problem?
Run BigQuery Query using Java API library. It will intermediately fail with 
timeout. 

What is the expected output? What do you see instead?
Response returned within 10 sec.

What version of the product are you using? On what operating system?
Java AppEngine

Please provide any additional information below.
The stack trace for failure is the following:

2013-06-07 17:05:31.006 /_ah/queue/__deferred__ 500 39253ms 0kb 
AppEngine-Google; (+http://code.google.com/appengine)

...

Caused by: com.electionear.fw.v2.shared.exception.DataAccessException: Can not 
obtain request result (Timeout while fetching URL: 
https://www.googleapis.com/bigquery/v2/projects/920037298476/queries)
    at [...].service.dataaccess.QueryBQVoterTableCommand.query(QueryBQVoterTableCommand.java:...)
    at [...].service.dataaccess.QueryBQVoterTableCommand.execute(QueryBQVoterTableCommand.java:...)
    at [...].service.DataAccessService.queryBQVotersTable(DataAccessService.java:...)
    at [...].service.DataAccessService$$FastClassByCGLIB$$3ac0c5b6.invoke(<generated>)
    at net.sf.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
    at org.springframework.aop.framework.Cglib2AopProxy$CglibMethodInvocation.invokeJoinpoint(Cglib2AopProxy.java:688)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
    at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:80)
    at com.electionear.fw.v2.server.util.profiler.ProfilerAspect.log(ProfilerAspect.java:28)
    at sun.reflect.GeneratedMethodAccessor37.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:45)
    at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:621)
    at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:610)
    at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:65)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:161)
    at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:80)
    at com.electionear.fw.v2.server.util.logger.LoggerAspect.log(LoggerAspect.java:55)
    at sun.reflect.GeneratedMethodAccessor36.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:45)
    at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:621)
    at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:610)
    at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:65)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:161)
    at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:90)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
    at org.springframework.aop.framework.Cglib2AopProxy$DynamicAdvisedInterceptor.intercept(Cglib2AopProxy.java:621)
    at com.electionear.fw.v2.server.service.DataAccessService$$EnhancerByCGLIB$$252cd130.queryBQVotersTable(<generated>)
    at com.electionear.fw.v2.server.tasks.bigquery.counters.RequestCountersTask.run(RequestCountersTask.java:40)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
    at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
    at com.googlecode.objectify.cache.AsyncCacheFilter.doFilter(AsyncCacheFilter.java:59)
    at com.googlecode.objectify.ObjectifyFilter.doFilter(ObjectifyFilter.java:49)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)

```

Original issue reported on code.google.com by `k.lebe...@electionear.com` on 10 Jun 2013 at 5:16

**Comment by GoogleCodeExporter** [comment]
```
Closing ticket due to age.  If you experience problems in the future, please 
open another ticket and include your project id and a relevant job id.  Thank 
you!
```

Original comment by `thomasp...@google.com` on 25 Apr 2014 at 6:35
- Changed state: **Done**
