### ISSUE TITLE
Sometimes getting java.net.SocketTimeoutException: SSL handshake timed out while inserting rows in bigquery from android app

### ISSUE THREAD

**Issue by GoogleCodeExporter** [runt18/google-bigquery#280]
```
What steps will reproduce the problem?
This is not always happening for me. Sometimes randomly it throws the error 
while inserting row to big query. I asked same question here also 
http://stackoverflow.com/questions/30978918/javax-net-ssl-sslhandshakeexception-
remote-host-closed-connection-during-handsh

What is the expected output? What do you see instead?
It should insert rows correctly but sometimes it fails then throws an error 
java.net.SocketTimeoutException: SSL handshake timed out

What version of the product are you using? On what operating system?
google-api-services-bigquery-v2-rev200-1.20.0.jar

Please provide any additional information below:-
Please find below non fatal error which we are getting sometimes randomly

java.net.SocketTimeoutException: SSL handshake timed out
       at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(NativeCrypto.java)
       at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:426)
       at com.android.okhttp.Connection.upgradeToTls(Connection.java:1014)
       at com.android.okhttp.Connection.connect(Connection.java:955)
       at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:411)
       at com.android.okhttp.internal.http.HttpEngine.sendSocketRequest(HttpEngine.java:343)
       at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:289)
       at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:345)
       at com.android.okhttp.internal.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:89)
       at com.android.okhttp.internal.http.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:197)
       at com.android.okhttp.internal.http.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:254)
       at com.google.a.a.c.a.c.a(NetHttpRequest.java:77)
       at com.google.a.a.c.r.p(HttpRequest.java:972)
       at com.google.a.a.b.d.c.b(AbstractGoogleClientRequest.java:419)
       at com.google.a.a.b.d.c.d(AbstractGoogleClientRequest.java:352)
       at com.google.a.a.b.d.c.e(AbstractGoogleClientRequest.java:469)
       at com.spiceladdoo.services.HeartBeatService.a(HeartBeatService.java:499)
       at com.spiceladdoo.services.HeartBeatService.onHandleIntent(HeartBeatService.java:186)
       at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:146)
       at android.os.HandlerThread.run(HandlerThread.java:61)
```

Original issue reported on code.google.com by `ajaysain...@gmail.com` on 8 Jul 2015 at 6:19

**Comment by GoogleCodeExporter** [comment]
```
Hi, sorry for the delayed response.  Are you still having this issue?

If so, could you provide us with some more information?

* Project id
* Dataset and table being inserted into
* Approximate times of error

Thank you,
```

Original comment by `thomasp...@google.com` on 25 Nov 2015 at 2:02
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
Closing due to no response in > 1 month.
```

Original comment by `thomasp...@google.com` on 30 Dec 2015 at 7:00
- Changed state: **Invalid**
