### ISSUE TITLE
StackOverflowError when reading Avro export from a table with complex schema

### ISSUE THREAD

**Issue by GoogleCodeExporter** [runt18/google-bigquery#381]
```
I exported a table with fairly complex schema (many repeated/nested fields) and 
got StackOverflowError when trying to read it with avro-tools tojson.

org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in 
stage 0.0 failed 4 times, most recent failure: Lost task 0.3 in stage 0.0 (TID 
3, 10.160.0.27): java.lang.StackOverflowError
    at org.apache.avro.io.parsing.Symbol$Sequence.flattenedSize(Symbol.java:323)
    at org.apache.avro.io.parsing.Symbol.flattenedSize(Symbol.java:216)
    at org.apache.avro.io.parsing.Symbol$Sequence.flattenedSize(Symbol.java:323)
    at org.apache.avro.io.parsing.Symbol.flattenedSize(Symbol.java:216)
    at org.apache.avro.io.parsing.Symbol$Sequence.flattenedSize(Symbol.java:323)
    at org.apache.avro.io.parsing.Symbol.flattenedSize(Symbol.java:216)
    at org.apache.avro.io.parsing.Symbol$Sequence.flattenedSize(Symbol.java:323)
    at org.apache.avro.io.parsing.Symbol.flattenedSize(Symbol.java:216)

This is also affecting AvroBigQueryInputFormat in bigquery-connector, filed in 
https://github.com/GoogleCloudPlatform/bigdata-interop/issues/16
```

Original issue reported on code.google.com by `nevi...@spotify.com` on 3 Dec 2015 at 6:02

**Comment by GoogleCodeExporter** [comment]
```
From:
https://github.com/GoogleCloudPlatform/bigdata-interop/issues/16

It sounds like you can reproduce using the BigQuery web UI at 
bigquery.cloud.google.com? If so, can you please provide a job id of a failing 
export job?
```

Original comment by `bch...@google.com` on 3 Dec 2015 at 7:43

**Comment by GoogleCodeExporter** [comment]
```
Here's the job ID:
di-bigquery-data-commons:job_rKdW9YbBQs0oz_hCpULy4D8rZ8E

The export job was actually successful but exception happens when I try to read 
the file with avro-tools.
```

Original comment by `nevi...@spotify.com` on 3 Dec 2015 at 7:45

**Comment by GoogleCodeExporter** [comment]
```
Indeed, the export job was successful. I believe the exported AVRO files should 
be available in your specified Google Cloud Storage bucket. This might be 
useful for the bigdata-interop folks to repro the issue.

I'm going to close this issue unless/until we know the issue is specific to 
BigQuery. I'll contact AngusDavis on the bigdata-interop team to share the 
relevant info for the export job.
```

Original comment by `bch...@google.com` on 3 Dec 2015 at 8:00
- Changed state: **WontFix**

**Comment by GoogleCodeExporter** [comment]
```
But the exported files are not readable by avro-tools which is part of Apache 
Avro, or other frameworks that support Avro like Spark.

`avro-tools getschema` works and prints schema.
`avro-tools tojson` causes exception.

Is there a chance that the output files are corrupted?
```

Original comment by `nevi...@spotify.com` on 3 Dec 2015 at 8:04

**Comment by GoogleCodeExporter** [comment]
```
Yes, that's a possibility, and I think we need the expertise of the 
bigdata-interop folks to help us determine that. I have sent them the relevant 
info for your export job to assist with their investigation.
```

Original comment by `bch...@google.com` on 3 Dec 2015 at 8:11
