### ISSUE TITLE
Google Compute Engines Fail to recognize GCE Metadata Credentials spontaneously

### ISSUE THREAD

**Issue by GoogleCodeExporter** [runt18/google-bigquery#387]
```
What steps will reproduce the problem?
1. I have cron jobs running continuously on ~120 GCEs They run pyton scripts to 
access and process data in Bigquery. After running without incident for weeks, 
these GCEs spontaneously and randomly begin reporting that the GCE Metadata 
credentials are invalid. Reseting the GCEs does not help. Sometimes redeploying 
the application helps but it's hit-or miss. Eventually I am forced to delete 
the instance and create a new one to resolve the issue.

The instance in question at the moment is: 
https://console.developers.google.com/compute/instancesDetail/zones/us-central1-
a/instances/rainman03?project=rising-ocean-426&graph=GCE_CPU&duration=PT1H


The code to obtain the credentials is:

        credentials = gce.AppAssertionCredentials(scope=SCOPE)

        # Create an httplib2.Http object to handle our HTTP requests and authorize it
        # with our good Credentials.
        http = credentials.authorize(httplib2.Http())
        gs_service = discovery.build(service, version, http=http)
        sys.stderr.write("Using GCE Metadata credentials\n")
        return gs_service

The error occurs not at the time the service is created but at the time the 
script attempts to use the service. The error is:

Using GCE Metadata credentials
Traceback (most recent call last):
  File "/usr/local/brightcove/rainman/python/metrics/update_metrics_big_query_job_status.py", line 178, in <module>
    main()
  File "/usr/local/brightcove/rainman/python/metrics/update_metrics_big_query_job_status.py", line 89, in main
    job = jobCollection.get(projectId='rising-ocean-426', jobId=jobId).execute()
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/util.py", line 132, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/apiclient/http.py", line 723, in execute
    raise HttpError(resp, content, uri=self.uri)
apiclient.errors.HttpError: <HttpError 401 when requesting 
https://www.googleapis.com/bigquery/v2/projects/rising-ocean-426/jobs/job_AX4Ri_
MiDuASIIthcbWF0UpBgfQ?alt=json returned "Invalid Credentials">





What is the expected output? What do you see instead?

I expect the GCE Metadata credentials to work consistently.

What version of the product are you using? On what operating system?

This is running on:

Machine type

f1-micro (1 vCPU, 0.6 GB memory)
CPU platform

Intel Sandy Bridge
Zone

us-central1-a
External IP

173.255.118.6 (ephemeral)
Internal IP

10.240.38.103

Please provide any additional information below.


```

Original issue reported on code.google.com by `gquino...@brightcove.com` on 8 Dec 2015 at 6:35

**Comment by GoogleCodeExporter** [comment]
```
Since this is an issue with credentials generated by GCE, I'd check with their 
support channels:

https://cloud.google.com/compute/docs/filereport

You may also find the new Application Default Credentials useful:

https://developers.google.com/identity/protocols/application-default-credentials
```

Original comment by `jcon...@google.com` on 11 Dec 2015 at 11:29
- Changed state: **WontFix**
