### ISSUE TITLE
Cannot access shared dataset when using the python client api

### ISSUE THREAD

**Issue by GoogleCodeExporter** [runt18/google-bigquery#497]
```
What steps will reproduce the problem?
1. Create a dataset in one project in account (a)
2. Share this dataset with a project in another account (b)
3. Create a service account in account b and give it view or editor permissions
4. Attempt to list the tables in the shared dataset using the python API

What is the expected output? What do you see instead?

I expect to see the list of tables for the shared dataset. Instead I get the 
following error:


Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.6/site-packages/oauth2client/util.py", line 137, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/googleapiclient/http.py", line 760, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 403 when requesting 
https://www.googleapis.com/bigquery/v2/projects/<projectId>/datasets/<datasetId>
/tables?alt=json returned "Access Denied: Dataset <projectId>:<datasetId>: The 
user <service account email> does not have permission to list tables in dataset 
<projectId>:<datasetId>">


What version of the product are you using? On what operating system?

OS:
CentOS release 6.7 (Final)

Python packages:
google-api-python-client (1.5.0)


Please provide any additional information below.

Using the user account (project owner) I can list the tables in the dataset 
using the UI or the bq command line tool

```

Original issue reported on code.google.com by `dbg.and...@gmail.com` on 7 Apr 2016 at 4:33

**Comment by GoogleCodeExporter** [comment]
Original comment by `wes...@google.com` on 13 Apr 2016 at 4:27
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
Could you share more information about step 2? What did you do to share the 
dataset with project B?

Note that dataset can only be shared with Principals - Project 
Owners/Editor/Viewer, gaia-id, domain, gaia-group etc. I am not aware of how to 
share a dataset with another "project".
```

Original comment by `nitsh...@google.com` on 14 Apr 2016 at 1:15
