### ISSUE TITLE
Dataset Creation Using Java throws 409 duplicate Google Json Error

### ISSUE THREAD

**Issue by GoogleCodeExporter** [runt18/google-bigquery#71]
```
What steps will reproduce the problem?
1. Using Java Client tools try to create a new dataset
2. Run program
3. Error appears as a GoogleJsonResponseException code 409 (see error dump 
below)

Note that the error occurs every single time I try to create a brand new 
dataset on my project "citrix-ws"

----------------------------------------

What is the expected output? What do you see instead?

Mar 3, 2014 9:26:25 PM com.citrix.ws.pipeline.server.web.map.RouterImpl$Route 
<clinit>
INFO: Added mapping for path: pipeline to handler: PipelineController
com.google.api.client.googleapis.json.GoogleJsonResponseException: 409 OK
{
  "code" : 409,
  "errors" : [ {
    "domain" : "global",
    "message" : "Already Exists: Dataset citrix-ws:migrations",
    "reason" : "duplicate"
  } ],
  "message" : "Already Exists: Dataset citrix-ws:migrations"
}
    at com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:145)
    at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:113)
    at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:40)
    at com.google.api.client.googleapis.services.AbstractGoogleClientRequest$1.interceptResponse(AbstractGoogleClientRequest.java:312)
    at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1049)
    at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:410)
    at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:343)
    at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:460)
    at com.citrix.ws.pipeline.server.web.model.Pipeline.processTestObject(Pipeline.java:281)
    at com.citrix.ws.pipeline.server.web.controller.PipelineController.execute(PipelineController.java:30)
    at com.citrix.ws.pipeline.server.web.map.RouterImpl.routeRequest(RouterImpl.java:175)
    at com.citrix.ws.pipeline.server.web.dispatch.DispatcherServlet.service(DispatcherServlet.java:57)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
    at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
    at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:390)
    at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
    at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
    at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
    at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
    at com.google.appengine.tools.development.DevAppEngineWebAppContext.handle(DevAppEngineWebAppContext.java:78)
    at org.mortbay.jetty.servlet.Dispatcher.include(Dispatcher.java:192)
    at com.opensymphony.sitemesh.compatability.OldDecorator2NewDecorator.render(OldDecorator2NewDecorator.java:46)
    at com.opensymphony.sitemesh.webapp.decorator.BaseWebAppDecorator.render(BaseWebAppDecorator.java:33)
    at com.opensymphony.sitemesh.webapp.SiteMeshFilter.doFilter(SiteMeshFilter.java:84)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at com.citrix.ws.toolkit.citrixkeyclient.api.web.filter.AbstractSingleSignOnFilter.doFilter(AbstractSingleSignOnFilter.java:197)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at com.google.appengine.tools.development.HeaderVerificationFilter.doFilter(HeaderVerificationFilter.java:35)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at com.google.appengine.api.blobstore.dev.ServeBlobFilter.doFilter(ServeBlobFilter.java:60)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at com.google.apphosting.utils.servlet.TransactionCleanupFilter.doFilter(TransactionCleanupFilter.java:43)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at com.google.appengine.tools.development.StaticFileFilter.doFilter(StaticFileFilter.java:122)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at com.google.appengine.tools.development.BackendServersFilter.doFilter(BackendServersFilter.java:97)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
    at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
    at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
    at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
    at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
    at com.google.appengine.tools.development.DevAppEngineWebAppContext.handle(DevAppEngineWebAppContext.java:78)
    at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
    at com.google.appengine.tools.development.JettyContainerService$ApiProxyHandler.handle(JettyContainerService.java:369)
    at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
    at org.mortbay.jetty.Server.handle(Server.java:326)
    at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
    at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
    at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:547)
    at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
    at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
    at org.mortbay.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.java:409)
    at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)
Mar 3, 2014 9:26:29 PM 
com.citrix.ws.toolkit.citrixkeyclient.api.web.filter.AbstractSingleSignOnFilter 
doFilter

---------------------
What version of the product are you using? On what operating system?
I'm using Windows 7
google-http-xxxx-1.17.0-rc
oauth jars 1.17.0-rc
bigquery v2 rev133-1.17.0-rc


------------------------------------

Please provide any additional information below.

CODE:

Dataset newDataset = new Dataset();
DatasetReference datasetRef = new DatasetReference();
datasetRef.setProjectId(PROJECT_ID);
datasetRef.setDatasetId(DATASET_ID);
newDataset.setDatasetReference(datasetRef);
Bigquery.Datasets.Insert datasetInsertion = 
bigquery.datasets().insert(PROJECT_ID, newDataset);
Dataset myDataset = datasetInsertion.execute();

response = "<div>New Datastore ID: "+myDataset.getId()+"</div>";

=======================
Thanks,

Camilo Silva
Web Services
Citrix Systems

```

Original issue reported on code.google.com by `camilo.s...@citrix.com` on 3 Mar 2014 at 9:35

**Comment by GoogleCodeExporter** [comment]
```
Just to clarify, the coding error only occurs whenever I try to create a brand 
new dataset from scratch. I'm testing locally with the Jetty Eclipse browser.

Thanks,
Camilo
```

Original comment by `camilo.s...@citrix.com` on 3 Mar 2014 at 9:40

**Comment by GoogleCodeExporter** [comment]
```
I forgot to mention an important detail:
even though the program fails with the GoogleJsonResponseException the dataset 
is still being successfully created - haha.

Many thanks for your help!
```

Original comment by `camilo.s...@citrix.com` on 3 Mar 2014 at 9:46

**Comment by GoogleCodeExporter** [comment]
```
I'm looking in our logs and seeing two separate dataset insert requests for 
recently-created datasets in project citrix-ws, including "migrations".  These 
requests look to be coming within about half a second of each other.

The code snippet you posted looks fine to me, but I wonder if your program may 
be making two separate insert requests for each dataset, resulting in an 
already exists exception on the second insert.
```

Original comment by `dk...@google.com` on 3 Mar 2014 at 10:09

**Comment by GoogleCodeExporter** [comment]
```
Hello Google Engineer,
You're quite right. I'm not sure why but the Eclipse Jetty local app of my 
project is sending 2 requests every single time. I'll try to find a way to 
investigate and resolve this.

Many thanks for your diligence and prompt response.
Sincerely,

Camilo
```

Original comment by `camilo.s...@citrix.com` on 5 Mar 2014 at 3:58

**Comment by GoogleCodeExporter** [comment]
```
Looks like this problem has been addressed. Please reopen if you need 
additional help!
```

Original comment by `jcon...@google.com` on 16 May 2014 at 7:09
- Changed state: **Done**
